# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '断点下载封装' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.2'
  # Pods for 断点下载封装

  target '断点下载封装Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '断点下载封装UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
